feat(to-match-screenshot): implementation
gemini-testing/playwright-utils pull request #2
Opened 2023-09-21 03:03 UTC by KuznetsovRoman

## Что сделано

Основная реализация команды. Перед влитием, нужно раскатить https://github.com/gemini-testing/looks-same/pull/95

2023-09-22 12:52 UTC, KuznetsovRoman commented on src/matchers/index.ts
> +
Использовать `extends Locator` не получится.

Такое позволяет иметь `toMatchScreenshot` только на локаторах

2023-09-22 12:53 UTC, KuznetsovRoman commented on src/matchers/index.ts
> +interface CustomMatchers<R, T> extends LocatorMatchersResolved<R, T> {}
Оставил на будущее, чтобы расширять тип `CustomMatchers`

2023-09-22 12:58 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/handlers.ts
> +import colors from "colors";
В этом файле - обработчики всех случаев. В большинстве своем они идентичны `playwright`-овским:
- Когда `isNot: true / false`
- Когда `snapshot` существует / не существует
- Когда картинка похожа / не похожа на референс

Исключение - `handleMissing`. `playwright` в таких случаях, когда `updateSnapshots === "all" || updateSnapshots === "missing"` дополнительно посчитает тест упавшим (хотя и продолжит его выполнение), но это реализовано через приватный метод и у нас такой возможности нет (поэтому, лог пишется и при `updateSnapshots === "missing"`, в то время как у `pw` его нет)

Еще, не стал реализовывать ту логику со "стабилизацией" скриншотов (когда переснимаем несколько). Если понадобится, можно сделать это отдельным PR

2023-09-22 12:59 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +export const createToMatchScreenshot = (
Функция, создающая сам матчер. Принимает тест и настройки на уровне проекта (выше дефолтных, ниже настроек на уровне ассерта)

2023-09-22 13:03 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +    return function toMatchScreenshot(locator, snapshotName, userOptions) {
Функция враппер. Имеет контекст и передает его в завернутую функцию. Помимо этого, создает полный `options` (чтобы не продумывать разные кейсы внутри), валидирует название снапшота

2023-09-22 13:04 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +export type ToMatchScreenshotMatcher<R> = (snapshotName: string, options?: Options) => Promise<R>;
Тип матчера - не то же самое, что и тип команды

2023-09-25 10:17 UTC, KuznetsovRoman reviewed
Изменил `README.md`

2023-09-25 10:17 UTC, KuznetsovRoman commented on README.md
> +Usefull [playwright][pwt] utilities, such as fixtures, custom commands and matchers.
Тут пофиксил: fixtures, `custom commands and matchers`

2023-09-25 10:17 UTC, KuznetsovRoman commented on README.md
>  # playwright-utils
Поменял название с `@gemini-testing/...`

2023-09-25 10:17 UTC, KuznetsovRoman commented on README.md
> +[looks-same][looks-same] based visual comparison. It uses [CIEDE2000][ciede2000] based tolerance instead of pixelmatch (which is used under the hood of `toHaveScreenshot`) [YIQ NTSC transmission colo
Тут дополнил про `toMatchScreenshot`

2023-09-25 10:17 UTC, KuznetsovRoman commented on README.md
> +```
Добавил установку

2023-09-25 10:27 UTC, KuznetsovRoman commented on README.md
> +<!-- END doctoc generated TOC please keep comment here to allow auto update -->
Добавил автосборку содержания

2023-09-27 10:23 UTC, DudaGod requested changes
- нет тестов (я бы наверное даже e2e докинул)
- есть баг со сравнением разных размеров скриншотов (летит ошибка)
- сейчас не очень удобно использовать (предлагаю через фикстуру реализовать)
- вроде думали о дефолтном использовании `expect.soft`, т.е. чтобы первый фейл скриншота не падал
- нет поддержки таймаутов
- не все опции подержаны из `toHaveScreenshot` (`threshold` не учитываем)
- названия скринов генерится по разному. Как пользователю практически бесшовно перейти с `toHaveScreenshot` на `toMatchScreenshot`?
- нет поддержки передачи `page` в `toMatchScreenshot`

В целом огонь. Нужно только немного допилить.

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +## Fixtures
А зачем пустые блоки оставлять? Я бы удалил

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +
А тут 2 пустых строки специально?

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +});
Я бы ожидал, что дефолтная конфигурация задавалась бы в основном конфиге `playwright.config.ts`, как это делается для `toHaveScreenshot` и для `toMatchSnapshot` - https://playwright.dev/docs/api/class-testproject#test-project-expect.

Для этого нужно реализовать фикстуру.

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +const toMatchScreenshot = createToMatchScreenshot(test, {
Необходимость передачи инстанса теста для получения необходимой функции тоже выглядит так себе.

Я бы это сделал внутри фикстуры в которой есть доступ к `testInfo`, т.е. спрятал бы эту настройку от юзера.

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +    interface Matchers<R, T> extends PwtUtilsMatchers<R,T, "toMatchScreenshot"> {}
С отступами перед `interface` проблема (выше юзал 2 пробела). Так же между `R,T` нужен пробел.

Но вообще я я бы все это тоже спрятал от юзера и делал бы внутри фикстуры.
Т.е. если пользователь заюзал фикстуру, то к нему сразу приезжает нужная команда и правильным образом расширяет `expect`.

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +    // Comparison config, optional
я бы тут явно написал, что у них приоритет выше

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +- stateName: `string`
Это наверное больше не `stateName`, а `screenshotName` (или даже просто `name`)? 
Вот так же лучше звучит - `expect locator to match screenshot name`, чем `expect locator to match screenshot state name`

2023-09-27 10:23 UTC, DudaGod commented on README.md
> +  - [caret][pwt-caret]: `"hide" | "initial"`
А это разве все доступные опции?

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/index.ts
> +
Я так и не понял почему просто заюзать `extends Locator` нельзя? Вижу, что он без проблем используется под капотом при реализации `toHaveScreenshot`

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/index.ts
> +interface CustomMatchers<R, T> extends LocatorMatchersResolved<R, T> {}
Выше писал, что я бы просто расширил `expect` под капотом фикстуры и тогда вот это все можно не делать

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/utils/fs.ts
> +export const exists = (filePath: string): Promise<boolean> =>
Как вариант можно было бы заюзать fs-extra - https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureFile.md

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/utils/fs.ts
> +export default { addSuffixToFilePath, writeFile, readFile, exists };
А зачем? Ты же выше каждый метод отдельно экспортишь (в файле ниже тоже похожий кейс)

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +    locator: Locator,
Здесь же может приезжать не только локатор, но и `page` (в этом случае снимается вьюпорт). Предлагаю поддержать такой вариант тоже (поддержан в дефолтном `toHaveScreenshot`).

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +    snapshotName: string,
А почему `snapshot`? Я бы назвал просто `name`

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +    userOptions?: Partial<Options>,
а зачем тут что-то про юзера? Почему просто не назвать `options`?

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +export type ToMatchScreenshotMatcher<R> = (snapshotName: string, options?: Partial<Options>) => Promise<R>;
В pwt для `toHaveScreenshot` поддержана возможность не передавать название файла и генерить его самому.

Может тоже поддержим?

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +type ToMatchScreenshot = (
Я бы еще для этого типа описал коммент (который по идее должен в тайпинги заезжать). Пример в pwt - https://github.com/microsoft/playwright/blob/main/packages/playwright/types/test.d.ts#L6531

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +export const createToMatchScreenshot = (
Если вынести логику в фикстуру, то кажется, что необходимости в этом методе нет.

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/index.ts
> +            return Promise.resolve({ pass: false, message: () => "A snapshot name is required" });
В pwt работает без этого.
Я бы наверное поддержал такую же логику. Чтобы юзеры могли спокойно перейти с дефолтного матчера использующего `pixelmatch` на наш. И чтобы ничего у них не сломалось. Т.е. подхватил бы теже самые скрины и API было бы похожим.

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/options.ts
> +export type Options = UserScreenshotOptions & UserCompareOptions & IgnoreDiffPixels;
А я тут не вижу всех возможных опций - https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-2. Например `isFullPage`, `quality`, `timeout` и т.д. Почему их не поддерживаем? Про `threshold` понятно, у нас свой `tolerance` есть.

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/toMatchScreenshotWrapped.ts
> +export async function toMatchScreenshotWrapped(
Я бы назвал просто `toMatchScreenshot` и экспортил наружу. В случае если по какой-то причине пользователь не хочет юзать фикстуры и хочет точечно заимпортить метод. Но в этом кейсе ему нужно будет самому думать как туда тест прокидывать.

Нужно подумать, возможно и не нужно такой вариант поддерживать.

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/toMatchScreenshotWrapped.ts
> +    });
Не хватает поддержки таймаута который выставляется в конфиге в секции `expect` или может быть передан в сам метод.

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/handlers.ts
> +        return { pass: true, message: () => message };
А почему у нас тут в случае если эталона нет, то тест проходит успешно? При использовании `toHaveScreenshot` тест фейлится. Видимо, чтобы юзер посмотрел явно глазами на снятый скриншот и если он ему не подходит, то сделал бы с ним что-то (переснял, удалил)

2023-09-27 10:23 UTC, DudaGod commented on src/matchers/to-match-screenshot/handlers.ts
> +        output.push(`    Diff: ${colors.yellow(diffPath)}`);
У pwt тоже такой отступ перед `Diff`?

2023-09-27 10:25 UTC, KuznetsovRoman commented on src/matchers/index.ts
> +
Потому что `extends Locator` тут внутри дает `false` абсолютно всегда, даже на сам локатор.

2023-09-27 19:45 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/utils/fs.ts
> +export default { addSuffixToFilePath, writeFile, readFile, exists };
Это чтоб можно было использовать `import moduleName from "..."` без звездочек

2023-09-27 19:46 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +    snapshotName: string,
Так было бы не очень понятно, `name` чего.

2023-09-27 19:48 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +    userOptions?: Partial<Options>,
Конфиг трехслойный:
- дефолты
- дефолты на уровне проекта (устанавливают пользователи один раз)
- конфиг на уровне вызова команды (устанавливает тот, кто ее вызывает)

Здесь явно видно, какие есть какие - `defaultOptions`, `projectOptions`, `userOptions`. При этом, это только мы видим, то есть у пользователя тут будет как раз просто `options`

<img width="455" alt="image" src="https://github.com/gemini-testing/playwright-utils/assets/54893992/999b157b-71ca-4fde-88be-4ffc8efc9da3">

2023-09-27 19:50 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +export type ToMatchScreenshotMatcher<R> = (snapshotName: string, options?: Partial<Options>) => Promise<R>;
https://nda.ya.ru/t/WHlbMlVE6kXszN

2023-09-27 19:58 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +            return Promise.resolve({ pass: false, message: () => "A snapshot name is required" });
В основном, я ее и добавил для облегчения перехода (чтобы не нужно было искать такие места)

Вроде договаривались сделать обязательным, потому что так правильнее

Да и чтобы такое сделать, нужно хранить мапку `[fullName, browserId] -> counter`

Для облегчения перехода, можно скрипт написать, который помимо замены названия самой команды еще и названия напишет, но делать такое необязательным - вообще не хочется, потому что это вызовет проблемы в дальнейшем (такие тесты без названия снапшота будут накапливаться)

2023-09-27 19:59 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/toMatchScreenshotWrapped.ts
> +export async function toMatchScreenshotWrapped(
Если даже он его и возьмет, его все равно нужно вставить в `expect`: такое апи. Иначе толку от возвращаемых `pass` и `message` не будет

2023-09-27 20:01 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/handlers.ts
> +        output.push(`    Diff: ${colors.yellow(diffPath)}`);
Да, поэтому его и сделал.
Отступ нужен для того, чтобы в консоль писались такие логи, где `:` стоит друг на друге и можно проще увидеть разницу в путях:

```
Expected: some/path/...
Received: some/path/...
    Diff: some/path/...
```

2023-09-27 20:03 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/handlers.ts
> +        return { pass: true, message: () => message };
Потому что `pw` для этого используют приватные методы, которые не экспортируются наружу (установить ошибку для теста, чтобы он продолжил выполняться, но в конце все равно упал с ней)

И у нас этих приватных методов нет

Если тут заменить `pass` на `false`, то в тесте с 5 снапшотами придется 5 раз запускать тест (а изнутри soft проставить не можем)

2023-09-27 20:03 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/options.ts
> +export type Options = UserScreenshotOptions & UserCompareOptions & IgnoreDiffPixels;
Нам точно нужен `quality`? Не выглядит полезным, если честно, но из-за него могут лететь фантомные диффы

2023-09-27 20:05 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/index.ts
> +type ToMatchScreenshot = (
Нет, в тайпинги заезжает `ToMatchScreenshotMatcher`, который ниже

2023-09-27 20:59 UTC, KuznetsovRoman commented on README.md
> +- stateName: `string`
Мне больше нравится `snapshotName`, потому что просто `name` непонятно, и `snapshotName` больше подходит, потому что такой нейминг у самого `playwright`

2023-09-27 21:00 UTC, KuznetsovRoman commented on src/matchers/to-match-screenshot/utils/fs.ts
> +export const exists = (filePath: string): Promise<boolean> =>
Когда я планировал сделать пакет с только этой командой, я хотел избежать лишних зависимостей. А так - да, можно было бы и `fs-extra` заюзать, но я бы уже так оставил

2023-09-27 21:01 UTC, KuznetsovRoman commented
@DudaGod 

В последних 4 коммитах сделал:
- совместимое с `toHaveScreenshot` имя
- добавил параметров (кроме `quality`)
- завернул в фикстуру. Как теперь используется - можно в `README.md` посмотреть
- добавил поддержку `expect(page).toMatchScreenshot`
- описал в документации дополнительные опции (теперь их 9):
```md
  - [tolerance][looks-same-tolerance]: `number`
  - [antialiasingTolerance][looks-same-antialiasing-tolerance]: `number`
  - [maxDiffPixels][pwt-max-diff-pixels]: `number`
  - [maxDiffPixelRatio][pwt-max-diff-pixels-ratio]: `number`
  - [animations][pwt-animations]: `"disabled" | "allow"`
  - [caret][pwt-caret]: `"hide" | "initial"`
  - [scale][pwt-scale]: `"css" | "device"`
  - [fullPage][pwt-full-page]: `boolean`
  - timeout: `number`
```

- https://github.com/gemini-testing/playwright-utils/pull/2#discussion_r1338368167: пока не реализуемо с использованием публичных АПИ
- https://github.com/gemini-testing/playwright-utils/pull/2#discussion_r1338306922: если использовать честные типы, то у пользователя будет ошибка "тип `node_modules/playwright/%%.Expect` не приводится к `node_modules/@gemini-testing/playwright-utils/%%.Expect`" и всякое такое. Не вижу особой проблемы с тем, что оно сейчас реализовано так, как реализовано
- https://github.com/gemini-testing/playwright-utils/pull/2#discussion_r1338341634: я бы оставил так, потому что "лучше сейчас, и придумать немного названий, чем потом и много". Мажор в будущем из-за этого катить не хочется, а сама эта возможность не указывать название снапшота мне не нравится (обсуждали в https://nda.ya.ru/t/WHlbMlVE6kXszN)

2023-09-28 09:34 UTC, KuznetsovRoman commented
Докинул два коммита: с юнит тестами и с включением CI workflow

2023-09-29 09:18 UTC, DudaGod approved these changes
В остальном вроде /ok
Перед влитием проверь, что переход с `toHaveScreenshot('foo.png')` на `toMatchScreenshot('foo.png')` не вызывает проблем

2023-09-29 09:18 UTC, DudaGod commented on .github/workflows/node.js.yml
> +    - run: npm test
Так а чего не накинуть еще и e2e тест с использованием браузера pwt, который будет просто ставится на агенте и выполнять тесты?

Позволит интеграционно проверить, что команда работает  и с ней нет никаких проблем. Так же может быть удобно для внешних пользователей. Которые хотят посмотреть рабочий пример использования.

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +const test = base.extend(createMatchersCombinedFixture(expect));
А почему в `base.extend` типы добавленных фикстур не прокидываешь?
Я ведь тогда в своей следующей фикстуре не смогу заюзать например добавленные тобой опции.
Типа такого:
```
const test = base.extend({
  ...createMatchersCombinedFixture(expect),
  foo: [async function ({ toMatchScreenshotOptions }, use) {
    console.log('toMatchScreenshotOptions:', toMatchScreenshotOptions); // any

    await use();
  }, { scope: "test", auto: true }],
});
```

Я бы вот так в пример добавил:
```
base.extend<PlaywrightTestOptions & ToMatchScreenshotOptions>
```

----

И я бы в примере так писал:
```
const test = base.extend({
    ...createMatchersCombinedFixture(expect)
});
```

Т.е. чтобы сразу была возможность еще фикстур докинуть.

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +import { createMatchersCombinedFixture } from "@gemini-testing/playwright-utils";
А чего такое название сложное? Почему не просто `addMatchersFixture`? Ну или хотя бы `createMatchersFixture`. Этот `combined` кажется совершенно лишним.

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +
лишний отступ

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +            timeout: 30000
Так может сюда добавить все дефолтные значения? (я к тому, что опций же больше)

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +    // Comparison config, have higher priority than project config, optional
Ну это же не конфиг. Это просто опции которые прокидываются в команду и имеют больший приоритет.

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +
Прикольно было бы добавить еще раздел с миграцией с `toHaveScreenshot` на `toMatchScreenshot`.

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +  - timeout: `number`
А ссылки на таймаут в pwt нет что ли?

2023-09-29 09:18 UTC, DudaGod commented on package.json
>          "@playwright/test": "1.36.1",
Уже вроде бы 1.37 вышла. Может апнет до latest?

2023-09-29 09:18 UTC, DudaGod commented on src/matchers/index.ts
> +interface LocatorMatchers<R> {
А разве в нем есть еще необходимость?

2023-09-29 09:18 UTC, DudaGod commented on src/matchers/index.ts
> +    [K in keyof LocatorMatchers<R>]: T extends PageLike | LocatorLike ? PageOrLocatorMatchers<R>[K] : never;
По идее вместо `LocatorMatchers` можно использовать `PageOrLocatorMatchers`, а `LocatorMatchers` выгасить

2023-09-29 09:18 UTC, DudaGod commented on src/matchers/index.ts
> +import { createToMatchScreenshotFixture } from "./to-match-screenshot";
А почему фикстуры не лежат отдельно в папке с фикстурами? Что они делают в матчерах?

2023-09-29 09:18 UTC, DudaGod commented on README.md
> +        toMatchScreenshotOptions: {
А не смотрел есть ли возможность докинуть в `expect` наши опции для `toMatchScreenshot`? Чтобы все `expect` опции в одном месте содержались.

Ну и вопрос зачем нам `options` в конце? Ведь его нет в `toHaveScreenshot` и в `toMatchSnapshot` - https://playwright.dev/docs/test-configuration#expect-options.

Предлагаю тоже без него указывать.

2023-09-29 09:18 UTC, DudaGod commented on src/matchers/to-match-screenshot/handlers.test.ts
> +        it("with updateSnapshots is 'missing'", () => {
Давай названия тестов писать с `should`, как мы это обычно делаем (и в остальных тестах тоже). А то по текущим названием не очень понятно, что должно произойти

2023-09-29 09:18 UTC, DudaGod commented on src/matchers/to-match-screenshot/options.test.ts
> +    it("should use default options", () => {
Хм, а здесь юзаешь `should ...`

2023-09-29 10:03 UTC, KuznetsovRoman commented on README.md
> +  - timeout: `number`
Это разные таймауты.

Тут вроде понятно, что за таймаут

У pwt это [другой таймаут](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-timeout): 

> Time to retry the assertion for in milliseconds

2023-09-29 10:04 UTC, KuznetsovRoman commented on src/matchers/index.ts
> +interface LocatorMatchers<R> {
Нет, убрал

2023-09-29 10:17 UTC, KuznetsovRoman commented on src/matchers/index.ts
> +import { createToMatchScreenshotFixture } from "./to-match-screenshot";
Фактически, все матчеры добавляются через фикстуру

Тут хотелось разделить фикстуры и матчеры, и в `/matchers` чтобы лежала фикстура, которая все матчеры связывает

Потому что если занести ее в фикстуры, то будет непонятно, че там делает фикстура с матчерами, если матчеры в отдельной папке лежат

Ровно как не хочется выносить `createToMatchScreenshotFixture` в папку с фикстурами, тут не хочется выносить фикстуру с созданием матчеров в папку с фикстурами

2023-09-29 11:41 UTC, KuznetsovRoman commented on README.md
> +import { createMatchersCombinedFixture } from "@gemini-testing/playwright-utils";
`add` - добавляет. Сама по себе функция выглядит так, как будто имеет сайд эффекты, но на самом деле - это чистая функция, она просто создает объект.

Переименую в `createMatchersFixture`

2023-09-29 11:55 UTC, KuznetsovRoman commented on .github/workflows/node.js.yml
> +    - run: npm test
Это нужно заносить e2e инфру, потому что с командой понадобится и сервер, который раздает какую-то страницу, и на этом сервере запускать команду. Можно сделать в рамках отдельной задачи, заносить e2e-инфру в этот PR не хочется

2023-09-29 12:15 UTC, KuznetsovRoman commented on package.json
>          "@playwright/test": "1.36.1",
Плохая идея, на самом деле.

Вот эти ошибки при попытке проверить, передают ли локатор, как раз от того, что типы не сходятся

Если в 1.37 playwright добавили какой-то метод в `Page` / `Locator`, то эти `Page` / `Locator` будут экстендить `PageLike` / `LocatorLike`. А если тут обновить до 1.37, то если у кого-то playwright версии 1.36, `Page` / `Locator` не будут экстендить `PageLike` / `LocatorLike`

2023-09-29 12:23 UTC, KuznetsovRoman commented on README.md
> +        toMatchScreenshotOptions: {
Такой возможности нет

options в конце уберу

2023-09-29 13:28 UTC, KuznetsovRoman commented on README.md
> +const test = base.extend(createMatchersCombinedFixture(expect));
Исправил

2023-09-29 17:12 UTC, merged